package co.edu.usc.vision.interacciones.dao.model;

import java.util.ArrayList;
import java.util.List;

public class DrugbankidExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public DrugbankidExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIsNull() {
            addCriterion("drugbank_id is null");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIsNotNull() {
            addCriterion("drugbank_id is not null");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdEqualTo(String value) {
            addCriterion("drugbank_id =", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotEqualTo(String value) {
            addCriterion("drugbank_id <>", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdGreaterThan(String value) {
            addCriterion("drugbank_id >", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdGreaterThanOrEqualTo(String value) {
            addCriterion("drugbank_id >=", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLessThan(String value) {
            addCriterion("drugbank_id <", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLessThanOrEqualTo(String value) {
            addCriterion("drugbank_id <=", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLike(String value) {
            addCriterion("drugbank_id like", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotLike(String value) {
            addCriterion("drugbank_id not like", value, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdIn(List<String> values) {
            addCriterion("drugbank_id in", values, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotIn(List<String> values) {
            addCriterion("drugbank_id not in", values, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdBetween(String value1, String value2) {
            addCriterion("drugbank_id between", value1, value2, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdNotBetween(String value1, String value2) {
            addCriterion("drugbank_id not between", value1, value2, "drugbankId");
            return (Criteria) this;
        }

        public Criteria andAtcIsNull() {
            addCriterion("atc is null");
            return (Criteria) this;
        }

        public Criteria andAtcIsNotNull() {
            addCriterion("atc is not null");
            return (Criteria) this;
        }

        public Criteria andAtcEqualTo(String value) {
            addCriterion("atc =", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotEqualTo(String value) {
            addCriterion("atc <>", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThan(String value) {
            addCriterion("atc >", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcGreaterThanOrEqualTo(String value) {
            addCriterion("atc >=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThan(String value) {
            addCriterion("atc <", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLessThanOrEqualTo(String value) {
            addCriterion("atc <=", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcLike(String value) {
            addCriterion("atc like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotLike(String value) {
            addCriterion("atc not like", value, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcIn(List<String> values) {
            addCriterion("atc in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotIn(List<String> values) {
            addCriterion("atc not in", values, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcBetween(String value1, String value2) {
            addCriterion("atc between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andAtcNotBetween(String value1, String value2) {
            addCriterion("atc not between", value1, value2, "atc");
            return (Criteria) this;
        }

        public Criteria andDrugbankIdLikeInsensitive(String value) {
            addCriterion("upper(drugbank_id) like", value.toUpperCase(), "drugbankId");
            return (Criteria) this;
        }

        public Criteria andAtcLikeInsensitive(String value) {
            addCriterion("upper(atc) like", value.toUpperCase(), "atc");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.drugbankid
     *
     * @mbggenerated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table usc.drugbankid
     *
     * @mbggenerated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }
    }
}